language: python


before_install:

    # Use utf8 encoding. Should be default, but this is insurance
    # against future changes
    - export PYTHONIOENCODING=UTF8
    - export MPLBACKEND=Agg

    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda  # get latest conda version
    - conda info -a # Useful for debugging any issues with conda

install:
    - conda env create --name test python=3.6
    - conda activate test
    - pip install -e .

script:
    - pytest


