name: ctaplot
channels:
  - conda-forge

dependencies:
  - astropy
  - ipywidgets
  - jupyter
  - matplotlib
  - nbsphinx
  - numpy
  - python > 3.6
  - pandas
  - scikit-learn
  - scipy
  - nbsphinx
  - pytables
  - pytest
